apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default "finansprotect" }}
  labels:
    name: {{ .Values.global.namespace | default "finansprotect" }}
    environment: {{ .Values.global.environment }}
    {{- include "finansprotect.labels" . | nindent 4 }}
