global:
  environment: staging

api:
  replicaCount: 2
  env:
    ENVIRONMENT: staging
    LOG_LEVEL: info

dashboard:
  replicaCount: 2

ingress:
  hosts:
    - host: api.staging.finansprotect.bg
      paths:
        - path: /
          pathType: Prefix
          service: api
    - host: app.staging.finansprotect.bg
      paths:
        - path: /
          pathType: Prefix
          service: dashboard
  tls:
    - secretName: finansprotect-staging-tls
      hosts:
        - api.staging.finansprotect.bg
        - app.staging.finansprotect.bg

persistence:
  auditLogs:
    size: 2Gi
  qemuDisk:
    size: 50Gi
